title: Hello, world! I'm Hunet-DataInnovation
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hunet-datainnovation.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Hunet-DataInnovation # add your name
author-img: hunetlogo.png # add your photo
about-author: 안녕하세요~ :)
Hunet DataInnovation팀
기술블로그입니다. # add description
#twitter: # add your Twitter handle
#facebook: # add your Facebook handle
github: "https://github.com/hunet-datainnovation/hunet-datainnovation.github.io" # add your Github handle
linkedin: # add your Linkedin handle
email: # add your Email address

# Disqus 댓글부분
#discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
